<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_ValidateSearchField__002</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cca5d9ab-531c-4243-a9c0-94f49090a794</testSuiteGuid>
   <testCaseLink>
      <guid>d9533062-5d39-4bfe-982d-5e1326dd3205</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTesting/Validate_searchfield_TC_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f7f9dc4e-9d8c-4a20-9a9f-34310c942abe</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data/TD_SearchFieldItem_002</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f7f9dc4e-9d8c-4a20-9a9f-34310c942abe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>1a03cece-b714-4181-ae85-c02e39ac0898</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f7f9dc4e-9d8c-4a20-9a9f-34310c942abe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>items</value>
         <variableId>c4de85af-826c-4d03-b5b5-36ad69cd985d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
