<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputnav-search-submit-button</name>
   <tag></tag>
   <elementGuidId>8bec516d-79ad-4eac-b621-51c92136832c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-search-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b80de40-808a-4376-af33-fda981248225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-submit-button</value>
      <webElementGuid>fa30b813-b9fe-4053-a764-b1d8e7fab6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>37cec8e5-cfeb-4098-aa52-6779c192498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>9da640dc-b782-4414-98bd-8ef435cd4fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>c7b5c4dd-ac22-46c0-ba0b-787bdd4abed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64e46321-9727-46c3-b87a-c67cbd2eb6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-submit-button&quot;)</value>
      <webElementGuid>f0ee09db-396f-44ad-8f32-bce50eaa33aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-submit-button']</value>
      <webElementGuid>272a1a99-5172-4e8b-a851-5abd14667ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nav-search-submit-text']/input</value>
      <webElementGuid>e61b995b-748e-4b06-a5a1-e4bba5f45fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>42691097-f4d7-49d2-8d98-631591eacb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nav-search-submit-button' and @type = 'submit']</value>
      <webElementGuid>4931d1f9-df84-4a02-9be3-1936dd67629a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
